name: global-configuration
version: 0.0.1
schema: v1
# https://docs.continue.dev/features/agent/model-setup
models:
  - name: Ollama Autodetect
    provider: ollama
    model: AUTODETECT

  - name: qwen2.5-coder
    provider: ollama
    model: qwen2.5-coder:7b-instruct-q6_K

  - name: SBER - GPT OSS 120B
    provider: openai
    model: openai/gpt-oss-120b
    apiKey: ${{ secrets.SBER_API_KEY }}
    apiBase: https://foundation-models.api.cloud.ru/v1
    defaultCompletionOptions:
      contextLength: 131072
    capabilities:
      - tool_use
    roles:
      - apply
      - chat
      - edit

  - name: qwen2.5-coder autocomplete local
    provider: ollama
    model: qwen2.5-coder:7b-instruct-q6_K
    roles:
      - autocomplete

  - name: nomic-embed-text latest
    provider: ollama
    model: nomic-embed-text:latest
    roles:
      - embed

  - name: SBER - qwen2.5-coder autocomplete 
    provider: nebius
    model: Qwen/Qwen2.5-Coder-32B-Instruct
    apiKey: ${{ secrets.SBER_API_KEY }}
    apiBase: https://foundation-models.api.cloud.ru/v1
    roles:
      - autocomplete

  - name: SBER - Qwen3-Coder-480B-A35B-Instruct
    provider: nebius
    model: Qwen/Qwen3-Coder-480B-A35B-Instruct
    apiKey: ${{ secrets.SBER_API_KEY }}
    apiBase: https://foundation-models.api.cloud.ru/v1
    roles:
      - autocomplete

context:
  - provider: file
  - provider: currentFile
  - provider: code
  - provider: codebase
    params:
      nRetrieve: 30
      nFinal: 10
  - provider: docs
  - provider: search
  - provider: diff
  - provider: folder
  - provider: terminal
rules:
  - Отвечай кратко и по существу
  - Всегда используй русский язык
prompts:
  - name: code_review
    description: Check for mistakes in my code
    prompt: >
      Please read the highlighted code and check for any mistakes. You should
      look for the following, and be extremely vigilant:
        - Syntax errors
        - Logic errors
        - Security vulnerabilities
        - Performance issues
        - Anything else that looks wrong
      Ответ нужен на русском языке.  
